ArticoApp/discover/urls.py
from django.urls import path, include

from ArticoApp.discover.views import IndexView, DiscoverView, DiscountsView

urlpatterns = (
    path('', IndexView.as_view(), name='index'),
    path('discover/', DiscoverView.as_view(), name='discover'),
    path('discounts/', DiscountsView.as_view(), name='discounts'),
)

ArticoApp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from ArticoApp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ArticoApp.discover.urls')),
    path('a/', include('ArticoApp.accounts.urls')),
    path('products/', include('ArticoApp.products.urls')),
    path('discounts/', include('ArticoApp.discounts.urls')),
    path('sales/', include('ArticoApp.sales.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ArticoApp/accounts/models.py
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.utils.text import slugify

from django.utils.translation import gettext_lazy as _
from django.contrib.auth import models as auth_models, get_user_model

from django.utils import timezone

from ArticoApp.accounts.managers import ArticoUserManager
from ArticoApp.products.models import MaxFileSizeValidator


# Create your models here.

# auth_models.AbstractUser

username_validator = UnicodeUsernameValidator()





class ArticoUser(AbstractBaseUser, auth_models.PermissionsMixin):
    SLUG_MAX_LENGTH = 50


    email = models.EmailField(
        _("email"),
        max_length=150,
        unique=True,

        validators=[username_validator],
        error_messages={
            "unique": _("A user with that email already exists."),
        },
    )
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )

    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    slug = models.SlugField(
        max_length=SLUG_MAX_LENGTH,
        unique=True, null=False,
        blank=True,
        editable= False,
    )

    USERNAME_FIELD = "email"

    objects = ArticoUserManager()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # 2 saves because by creating model id is none and slug id is equal none
        if not self.slug:
            self.slug = slugify(f'author-{self.id}')
        super().save(*args, **kwargs)



class Profile(models.Model):
    SIZE_3_MB = 3 * 1024 * 1024

    MAX_USERNAME_LENGTH = 64
    MAX_FIRST_NAME_LENGTH = 30
    MAX_lAST_NAME_LENGTH = 50

    username = models.CharField(
        max_length= 64,
        blank=True,
        null=False,
    )

    first_name = models.CharField(
        max_length=MAX_FIRST_NAME_LENGTH,
        blank=True,
        null=True
    )

    last_name = models.CharField(
        max_length=MAX_FIRST_NAME_LENGTH,
        blank=True,
        null=True,
    )

    bio = models.TextField(
        blank=True,
        null=True
       )


    profile_photo = models.ImageField(upload_to = 'profile_photo/',
        null=False,
        blank=False,
        validators=(
        MaxFileSizeValidator(limit_value = SIZE_3_MB),
        )


    )


    date_of_birth = models.DateField(
        blank=True,
        null=True
    )

    user = models.OneToOneField(
        ArticoUser,
        primary_key=True,
        on_delete=models.CASCADE,
    )


class UserFollow(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING)

ArticoApp/discover/models.py
from django.db import models

# Create your models here.

ArticoApp/products/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from django.core.validators import BaseValidator

from ArticoApp.core.models import IHaveUser

# Create your models here.
SIZE_5_MB = 5*1024*1024

print(settings.AUTH_USER_MODEL)
class MaxFileSizeValidator(BaseValidator):
    def clean(self, x):
        return x.size

    def compare(self, file_size, max_size):
        return max_size < file_size


class Product(IHaveUser, models.Model):
    MAX_LENGTH = 300
    SLUG_MAX_LENGTH = 20
    class Category(models.TextChoices):
        PAINTINGS = 'Paintings', 'Paintings'
        SCULPTURES = 'Sculptures', 'Sculptures'
        PHOTOGRAPHY = 'Photography', 'Photography'
        JEWELRY = 'Jewelry', 'Jewelry'
        TOYS = 'Toys', 'Toys'
        DIGITAL_ART = 'Digital Art', 'Digital Art'
        OTHER = 'Other', 'Other'





    name = models.CharField(
        max_length= MAX_LENGTH,
        null=False,
        blank=False
    )

    category = models.CharField(
        max_length=50,
        choices=Category.choices,
        default=Category.OTHER,
    )

    copies = models.IntegerField(default=1,
                                 null=False,
                                 blank=False
                                 )

    short_description = models.TextField()

    long_description = models.TextField()

    product_photo = models.ImageField(upload_to = 'product_photo/',
        null=False,
        blank=False,
        validators=(
        MaxFileSizeValidator(limit_value = SIZE_5_MB),
        )

    )


    slug = models.SlugField(
        max_length=SLUG_MAX_LENGTH,
        unique=True, null=False,
        blank=True,
        editable= False,
    )

    price = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True, #on every save

    )





    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # 2 saves because by creating model id is none and slug id is equal none
        if not self.slug:
            self.slug = slugify(f'prod-{self.name}-{self.id}')
        super().save(*args, **kwargs)



class ProductLike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

ArticoApp/discover/views.py
import random

from django.contrib.auth import get_user_model


from ArticoApp.accounts.models import Profile
from ArticoApp.discounts.models import Discount
from ArticoApp.products.models import Product
from django.views import generic as views, View


UserModel = get_user_model()



class IndexView(views.ListView):
    queryset = Product.objects.all()



    def get_template_names(self):
        if self.request.user.is_authenticated:
            # User is authenticated
            return ['discover/index-user.html']
        else:
            # User is not authenticated
            return ['discover/index.html']
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not self.request.user.is_authenticated:


            all_products = Product.objects.all()
            products_with_discount = []
            products_without_discount = []

            if all_products:
                for product in all_products:
                    if Discount.objects.filter(product_id=product.pk):
                        products_with_discount.append(product)
                    else:
                        products_without_discount.append(product)

            first_product = products_with_discount[0]
            second_product = products_without_discount[0]



            context.update({
                'products': all_products,
                'first_product': first_product,
                'second_product': second_product,
            })
        else:

            products = Product.objects.order_by('?')[:10]
            user_products = Product.objects.filter(user=self.request.user)

            top_sellers = Profile.objects.order_by('user_id')[:10]

            top_authors = Profile.objects.order_by('user_id')[:4]



            # sort_top_authors(top_authors)


            context.update({
                'products': products,
                'user_products': user_products,
                'top_sellers': top_sellers,
                'top_authors': top_authors,
            })

        return context


class DiscoverView(views.ListView):
    queryset = Product.objects.all()
    template_name = 'discover/discover-1.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()

        context.update({
            'products': products,

        })

        return context

class DiscountsView(views.ListView):
    queryset = Product.objects.all()
    template_name = 'discover/discounts-products.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        all_products = Product.objects.all()

        products_with_discount = []

        if all_products:
            for product in all_products:
                if Discount.objects.filter(product_id=product.pk):
                    products_with_discount.append(product)


        context.update({
            'products_with_discount': products_with_discount,
        })

        return context

templates/discover/banner-user-items.html
{% for product in user_products %}


                            <div class="banner-item">
                                <div class="banner-item-img">
                                    <img src="{{ product.product_photo.url }}" alt="Images">

                                </div>

                                <div class="content">
                                    <h3>{{ product.name }}</h3>
                                    <p><i class="ri-heart-line"></i> {{ product.productlike_set.count }}</p>
                                    <div class="banner-item-content">
                                        <div class="item-left">
                                            <span>Price</span>
                                            <h3 class="item-left-eth">{{ product.price }}</h3>
                                        </div>
                                        <div class="item-right">
                                            <h3 class="item-remaining">{{ product.category }}</h3>
                                            <h3 class="item-remaining">{{ product.short_description }}</h3>
                                        </div>
{#                                        add promotion counter if have#}
{#                                        <div class="item-right">#}
{#                                            <h3 class="item-remaining">Remaining Time</h3>#}
{#                                            <div class="timer-text" data-countdown="2022/11/11"></div>#}
{#                                        </div>#}
                                    </div>
                                    <a href="{% url 'details-product' username=request.user product_slug=product.slug %}" class="place-btn">Details</a>
                                </div>
                            </div>




{% endfor %}

templates/discover/discover-product.html
{% for product in discover_products %}

                                <div class="col-lg-3 col-md-6">
                                    <div class="featured-item">
                                        <div class="featured-item-img">
                                            <a href="{% url 'details-product' username=product.user.email product_slug=product.slug %}">
                                                <img src="{{ product.product_photo.url }}" alt="Images">
                                            </a><div class="featured-user">
                                                <a href="{% url 'author-profile' pk=product.user.pk %}" class="featured-user-option">
                                                    <img src="{{product.user.profile.profile_photo.url}}" alt="Images">
                                                    <span>@{{ product.user.profile.username  }}</span>
                                                </a>
                                            </div>
                                        {% if product.discounts %}

                                            <button type="button" class="default-btn border-radius-5">{{ product.discounts.price_with_discount }} $</button>
                                            <div class="featured-item-clock" data-countdown="{{ product.discounts.discount_end_date | date:'Y/m/d'  }}"></div>
                                        {% endif %}
                                        </div>

                                        <div class="content">
                                            <h3><a href="../product/author-profile.html">Industrial Revolution</a></h3>
                                            <div class="content-in">
                                                <span>{{ product.short_description }}</span>
                                                <h4>{{ product.price }} $</h4>
                                            </div>
                                            <div class="featured-content-list">

                                            </div>
                                        </div>
                                    </div>
                                </div>
{% endfor %}

templates/discover/index-user.html
{% extends 'partials/base.html' %}
{% load static %}


{% block main_content %}

        <!-- Main Banner Area -->
        <div class="banner-area-two">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-lg-6">
                        <div class="banner-content-two">
                            <h1> Explore, buy, and sell original artworks on our vibrant platform.</h1>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam etiam rhoncus aenean a iaculis aliquet accumsan sodales consectetur.
                            </p>
                            <div class="banner-btn">
                                <a href="{% url 'create-product' %}" class="default-btn border-radius-5">Create your Product</a>
                            </div>
                        </div>
                    </div>

                    {% if user_products %}

                    <div class="col-lg-6">
                        <div class="banner-item-slider owl-carousel owl-theme">

                         {% include 'discover/banner-user-items.html' with products=user_products %}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>

            <div class="banner-shape">
                <div class="shape-in1">

                    <img src="{% static '/images/home-two/home-two-shape1.png' %}" alt="Item">
                </div>
                <div class="shape-in2">
                    <img src="{% static '/images/home-two/home-two-shape2.png' %}" alt="Item">

                </div>
            </div>
        </div>
        <!-- Main Banner Area End -->

        <!-- Trending Area -->
        <div class="trending-area pt-100 pb-70">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-7">
                        <div class="section-title">
                            <h2>Trending Artwork</h2>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-5">
                        <div class="trending-btn text-end">
                            <a href="../product/item-details.html" class="default-btn border-radius-5">Explore More</a>
                        </div>
                    </div>
                </div>

                <div class="trending-slider owl-carousel owl-theme pt-45">
                     {% include 'product/product-card.html' with photo_list=products %}
                </div>
            </div>
        </div>
        <!-- Trending Area End -->>

        <!-- Top Sellers Area -->

        <div class="top-sellers-area pb-70">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-6">
                        <div class="section-title">
                            <h2>Top Sellers</h2>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="trending-btn text-end">
                            <a href="authors.html" class="default-btn border-radius-5">Explore More</a>
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center pt-45">

                    {% if top_sellers %}
                         {% include 'discover/top-sellers-card.html' with sellers=top_sellers %}
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Top Sellers Area End -->





        <!-- Testimonial Area -->
        <div class="testimonial-area ptb-100">
            <div class="container">
                <div class="testimonial-slider owl-carousel owl-theme">
                    <div class="testimonial-item">
                        <div class="testimonial-img">
                            <img src="{% static '/images/testimonial/testimonial-img.png' %}" alt="Images">
                        </div>

                        <div class="testimonial-content">
                            <img src="{% static '/images/testimonial/testimonial-line.png' %}" alt="Images">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Elementum lacus, tempus aliquam turpis diam amet leo enim. Nisi enim lorem condimentum tincidunt ornare nam adipiscing. Volutpat lacus, est hendrerit elit sed interdum.</p>
                            <ul>
                                <li>Rennie Wood </li>
                                <li>Founder</li>
                            </ul>
                        </div>
                    </div>

                    <div class="testimonial-item">
                        <div class="testimonial-img">

                            <img src="{% static '/images/testimonial/testimonial-img2.png' %}" alt="Images">
                        </div>

                        <div class="testimonial-content">

                            <img src="{% static '/images/testimonial/testimonial-line.png' %}" alt="Images">

                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Elementum lacus, tempus aliquam turpis diam amet leo enim. Nisi enim lorem condimentum tincidunt ornare nam adipiscing. Volutpat lacus, est hendrerit elit sed interdum.</p>
                            <ul>
                                <li>Macie Mood </li>
                                <li>Ex Manager</li>
                            </ul>
                        </div>
                    </div>

                    <div class="testimonial-item">
                        <div class="testimonial-img">

                            <img src="{% static '/images/testimonial/testimonial-img3.png' %}" alt="Images">
                        </div>

                        <div class="testimonial-content">

                            <img src="{% static '/images/testimonial/testimonial-line.png' %}" alt="Images">

                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Elementum lacus, tempus aliquam turpis diam amet leo enim. Nisi enim lorem condimentum tincidunt ornare nam adipiscing. Volutpat lacus, est hendrerit elit sed interdum.</p>
                            <ul>
                                <li>Olivia Jenar</li>
                                <li>CEO and Director</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Testimonial Area End -->

        <!-- Author Area -->

     {% if top_authors %}


        <div class="author-area author-area-bg2 pt-100 pb-70">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-8 col-md-6">
                        <div class="section-title">
                            <h2>Top Author</h2>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="author-btn text-end">
                            <a href="authors.html" class="default-btn border-radius-5">Explore More</a>
                        </div>
                    </div>
                </div>

                <div class="row pt-45 justify-content-center">
                     {% if top_authors %}
                        {% include 'discover/top-authors-card.html' with authors=top_authors %}
                    {% endif %}
                </div>
            </div>
        </div>
     {% endif %}
    <!-- Author Area End -->




{% endblock %}

templates/discover/top-authors-card.html
{% for author in authors %}

                    <div class="col-lg-3 col-6">
                        <div class="author-item">
                            <a href="{% url 'author-profile' pk=author.user_id %}">
                                <img src="{{ author.profile_photo.url }}" alt="Images">
                            </a>
                            <div class="content">
                                <div class="author-user-list">

                                    <div class="author-user-content">
                                        <h3><a href="author-profile.html">{{ author.first_name }} {{ author.last_name }}</a></h3>
                                        <span>@{{ author.username }}</span>
                                    </div>
                                </div>
    
                                <div class="author-content">
                                    <div class="content-left">
                                        <span>Followers</span>
                                        <h4>{{ author.userfollow_set.count }}</h4>
                                    </div>


                                         <a href="{% url 'follow-user' pk=author.user_id %}"><div class="content-right">Follow</div></a>

                                </div>
                            </div>
                        </div>
                    </div>
{% endfor %}

templates/discover/top-sellers-card.html
{% for seller in sellers %}

                    <div class="col-lg-3 col-6 col-md-4">
                        <div class="top-sellers-item">
                            <div class="top-sellers-img">
                                <a href="{% url 'author-profile' pk=seller.user_id %}">
                                    <img src="{{ seller.profile_photo.url }}" alt="Images">
                                </a>
                                <i class="ri-check-line"></i>
                            </div>
                            <div class="content">
                                <h3><a href="{% url 'author-profile' pk=seller.user_id %}">{{ seller.first_name }} {{ seller.last_name }}</a></h3>
                                <span>@{{ seller.username }}</span>
                            </div>
                        </div>
                    </div>
{% endfor %}